### ISSUE TITLE
Only show enabled connections in dropdown select

### ISSUE THREAD

**Issue by jakeprins** [apideck-samples/crm#8]
We could still show them but give them some sort of status check. 

![select-states](https://user-images.githubusercontent.com/1112129/112404733-2df62a80-8d11-11eb-9462-242d21e08bc4.png)

Color states
- Blue: added 
- Grey: disabled --> clicking on it would deep-link to the HV
- Green (later): fully configured healthy connection 

If I can recall correctly Tailwind UI has a select element like this. Can it be made searchable?

**Comment by Gdewilde** [comment]
@jakeprins updated requirements
